name: Generate and Deploy OPML Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # v2 yerine daha güncel v3 kullanıldı

    - name: Set up Python
      uses: actions/setup-python@v4 # v2 yerine daha güncel v4 kullanıldı
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    - name: Run OPML generation script
      run: python transform_to_opml.py

    - name: List OPML files
      id: list_opml_files
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        BASE_URL="https://${{ github.actor }}.github.io/${REPO_NAME}"
        # opml_urls.txt dosyasını oluşturmadan önce mevcutsa temizle
        > opml_urls.txt
        for FILE in *.opml; do
          echo "${BASE_URL}/${FILE}" >> opml_urls.txt
        done
        cat opml_urls.txt

    # GitHub Pages için yeni dağıtım adımları
    # Önce dağıtılacak dosyaları bir artifact olarak yükleyin
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3 # GitHub Pages için artifact yükleme eylemi
      with:
        path: './' # Deponuzun kök dizinindeki tüm dosyaları dağıtılacak olarak işaretler.
                   # Eğer sadece belirli bir klasördeki (örn: 'build' veya 'public') dosyaları dağıtmak istiyorsanız,
                   # yolu buna göre değiştirin. Sizin durumunuzda './' doğru görünüyor.

    # Ardından bu artifact'ı GitHub Pages'e dağıtın
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 # GitHub Pages'e dağıtım eylemi
      # permissions:
      #   pages: write
      #   id-token: write
      # Yukarıdaki izinler, eğer iş akışınızda zaten tanımlı değilse,
      # bu adımın çalışması için repository settings -> Actions -> General -> Workflow permissions altında
      # "Read and write permissions" seçeneğinin işaretli olduğundan emin olun.
      # Ya da doğrudan bu job için permissions tanımlayabilirsiniz.

    - name: Display OPML URLs
      run: |
        echo "OPML dosyalarının URL'leri:"
        cat opml_urls.txt

    - name: Upload grouped OPML file
      uses: actions/upload-artifact@v3
      with:
        name: grouped-feeds
        path: grouped_feeds.opml

    - name: Upload individual OPML files
      uses: actions/upload-artifact@v3
      with:
        name: individual-feeds
        path: '*.opml'
        if-no-files-found: error

    - name: Upload OPML URLs
      uses: actions/upload-artifact@v3
      with:
        name: opml-urls
        path: opml_urls.txt
