name: Generate and Deploy OPML Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    - name: Run OPML generation script
      run: python transform_to_opml.py

    - name: List OPML files
      id: list_opml_files
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        BASE_URL="https://${{ github.actor }}.github.io/${REPO_NAME}"
        for FILE in *.opml; do
          echo "${BASE_URL}/${FILE}" >> opml_urls.txt
        done
        cat opml_urls.txt

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: |
          .github/**
          README.md
          transform_to_opml.py

    - name: Display OPML URLs
      run: |
        echo "OPML dosyalarının URL'leri:"
        cat opml_urls.txt

    - name: Upload grouped OPML file
      uses: actions/upload-artifact@v3
      with:
        name: grouped-feeds
        path: grouped_feeds.opml

    - name: Upload individual OPML files
      uses: actions/upload-artifact@v3
      with:
        name: individual-feeds
        path: '*.opml'
        if-no-files-found: error

    - name: Upload OPML URLs
      uses: actions/upload-artifact@v3
      with:
        name: opml-urls
        path: opml_urls.txt